name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Install Cordova & Android Tools
      run: |
        npm install -g cordova
        sudo apt-get update
        sudo apt-get install -y android-sdk

    - name: Create Mobile Wrapper
      run: |
        cordova create myapp com.checklist.its CheklistITS
        cd myapp
        cordova platform add android --no-telemetry
        
        # Очищаем дефолтные файлы и копируем ваш index.html
        rm -rf www/*
        cp -r ../* www/ || true
        rm -rf www/myapp www/node_modules
        
        # Запускаем сборку
        cordova build android --device --no-telemetry

    - name: Find and Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: checklist-apk
        path: |
          myapp/platforms/android/app/build/outputs/apk/**/*.apk
          **/*.apk
        if-no-files-found: error
